# Generated by Django 6.0.6 on 2026-07-01 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU / Código de Barras')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('unidad_medida', models.CharField(choices=[('PZA', 'Pieza'), ('KG', 'Kilogramo'), ('LTS', 'Litro'), ('MET', 'Metro')], default='PZA', max_length=3, verbose_name='Unidad de Medida')),
                ('costo_ultimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Último Costo de Compra')),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Promedio')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio de Venta (Antes de Impuestos)')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Mínimo (Alerta)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('moneda_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_costo', to='general.moneda', verbose_name='Moneda de Costo')),
                ('moneda_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_venta', to='general.moneda', verbose_name='Moneda de Venta')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
