# Generated by Django 6.0.6 on 2026-07-17 20:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_crear_roles_erp'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bodega / Almacén',
                'verbose_name_plural': 'Bodegas / Almacenes',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Catálogo de Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='costo_promedio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='costo_ultimo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='moneda_costo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='moneda_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_promedio_mxn',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Costo promedio unitario en MXN para contabilidad', max_digits=18),
        ),
        migrations.AddField(
            model_name='producto',
            name='moneda_base_costo',
            field=models.ForeignKey(default=1, help_text='Moneda en la que se rastrea el costo promedio', on_delete=django.db.models.deletion.PROTECT, related_name='productos_costo', to='general.moneda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='moneda_base_venta',
            field=models.ForeignKey(default=1, help_text='Moneda de referencia para precios de venta', on_delete=django.db.models.deletion.PROTECT, related_name='productos_venta', to='general.moneda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MP', 'Materia Prima (Químicos/Hojalata)'), ('CP', 'Componente (Válvulas/Tapas)'), ('PT', 'Producto Terminado (Botes/Aerosol)')], default='PT', max_length=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(help_text='Ej: AE-001 (Aerosol) o MP-BAR-EPO (Barniz)', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('E', 'Entrada (Compra/Producción)'), ('S', 'Salida (Venta/Consumo)'), ('T', 'Transferencia entre Bodegas'), ('A', 'Ajuste Manual')], max_length=1)),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=18)),
                ('costo_unitario_mxn_capturado', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Costo unitario en MXN al momento del movimiento', max_digits=18)),
                ('referencia_operacion', models.CharField(blank=True, help_text='Ej: Folio OC-2026-004 o OP-2026-001', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='inventario.bodega')),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='inventario.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el movimiento', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario (Kardex)',
                'verbose_name_plural': 'Movimientos de Inventario (Kardex)',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(help_text='Ej: Pza, Kg', on_delete=django.db.models.deletion.PROTECT, to='inventario.unidadmedida'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('ubicacion_especifica', models.CharField(blank=True, help_text='Ej: Pasillo A, Estante 4', max_length=50, null=True)),
                ('stock_minimo', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Alerta de stock mínimo', max_digits=18)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Existencia (Stock)',
                'verbose_name_plural': 'Existencias por Ubicación',
                'unique_together': {('producto', 'bodega')},
            },
        ),
    ]
