# Generated by Django 6.0.6 on 2026-08-04 20:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_crear_roles_erp'),
        ('inventario', '0002_bodega_unidadmedida_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='costo_unitario_original',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Costo en la moneda de origen al momento del movimiento', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_caducidad',
            field=models.DateField(blank=True, help_text='Fecha de caducidad aplicable según el lote', null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.CharField(blank=True, help_text='Número de Lote (crítico para Químicos/Componentes)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='moneda_original',
            field=models.ForeignKey(blank=True, help_text='Moneda original de la transacción (Ej: USD en compra de válvulas)', null=True, on_delete=django.db.models.deletion.PROTECT, to='general.moneda'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tipo_cambio_aplicado',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Tipo de cambio del DOF aplicado ese día', max_digits=18),
        ),
        migrations.AddField(
            model_name='stock',
            name='cantidad_reservada',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Stock apartado para Órdenes de Producción o Pedidos de Venta', max_digits=18),
        ),
        migrations.AddField(
            model_name='stock',
            name='fecha_ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='costo_unitario_mxn_capturado',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Costo resultante en MXN integrado a la contabilidad', max_digits=18),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda_base_costo',
            field=models.ForeignKey(help_text='Moneda en la que se rastrea el costo promedio', on_delete=django.db.models.deletion.PROTECT, related_name='productos_costo', to='general.moneda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda_base_venta',
            field=models.ForeignKey(help_text='Moneda de referencia para precios de venta', on_delete=django.db.models.deletion.PROTECT, related_name='productos_venta', to='general.moneda'),
        ),
    ]
