# Generated by Django 6.0.6 on 2026-08-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario_costo_unitario_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MP', 'Materia Prima (Materiales de Empaque/Cobre/Bzniz)'), ('CP', 'Componente (Conos/Fondos/Boq./Válvulas)'), ('PT', 'Producto Terminado (Botes Aerosol,Alcoholero,Pintura)'), ('HJ', 'Hojalata en cuadro/litografia')], default='PT', max_length=2),
        ),
    ]
