# Generated by Django 6.0.6 on 2026-08-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MP', 'Materia Prima (Materiales de Empaque/Cobre/Bzniz)'), ('CP', 'Componente (Conos/Fondos/Boq./Válvulas)'), ('PT', 'Bote Terminado (Aerosol,Alcoholero,Pintura)'), ('HL', 'Hojalata Plain'), ('LL', 'Litografiada / Barnizada'), ('CC', 'Cuerpos Cortados')], default='PT', max_length=2),
        ),
    ]
