# Generated by Django 6.0.6 on 2026-09-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MP', 'Materia Prima (Materiales de Empaque/Cobre/Bzniz)'), ('CP', 'Componente (Conos/Fondos/Boq./Válvulas)'), ('PT', 'Bote Terminado (Aerosol,Alcoholero,Pintura)'), ('HR', 'Hojalata Rollo'), ('HL', 'Hoja (Litografiada / Barnizada)'), ('HC', 'Hoja Cortada Plain'), ('CC', 'Plantilla(Cuerpos Cortados)')], default='PT', max_length=2),
        ),
    ]
