# Generated by Django 6.0.6 on 2026-09-17 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='es_anulado',
            field=models.BooleanField(default=False, help_text='Indica si este movimiento fue anulado formalmente mediante contra-asiento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='es_contraasiento',
            field=models.BooleanField(default=False, help_text='Indica si este movimiento es un contra-asiento de reversa para anular otro movimiento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='movimiento_relacionado',
            field=models.ForeignKey(blank=True, help_text='Referencia al movimiento original si es contra-asiento, o al contra-asiento si fue anulado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contraasientos', to='inventario.movimientoinventario'),
        ),
        migrations.CreateModel(
            name='SolicitudAnulacionMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Folio secuencial ej: ANUL-2026-0001', max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de Autorización'), ('APR', 'Aprobada y Aplicada al Kardex'), ('REC', 'Rechazada')], default='PEN', max_length=3)),
                ('motivo_solicitud', models.TextField(help_text='Justificación operativa obligatoria para solicitar la anulación')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_administrador', models.TextField(blank=True, help_text='Comentarios o justificación del administrador', null=True)),
                ('movimiento', models.ForeignKey(help_text='Movimiento del Kardex que se solicita anular', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_anulacion', to='inventario.movimientoinventario')),
                ('movimiento_contraasiento', models.ForeignKey(blank=True, help_text='Movimiento inverso generado en el Kardex al aprobarse la anulación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='inventario.movimientoinventario')),
                ('usuario_autoriza', models.ForeignKey(blank=True, help_text='Administrador que aprobó o rechazó la solicitud', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anulaciones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(help_text='Usuario que solicita la anulación', on_delete=django.db.models.deletion.PROTECT, related_name='anulaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Anulación de Movimiento',
                'verbose_name_plural': 'Solicitudes de Anulación de Movimientos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
