# Generated by Django 6.0.6 on 2026-10-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_movimientoinventario_es_anulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clave_sat',
            field=models.CharField(default='24121800', help_text='Clave de producto/servicio SAT (ej. 24121800 para empaques y envases metálicos)', max_length=10, verbose_name='Clave SAT Prod/Serv'),
        ),
        migrations.AddField(
            model_name='producto',
            name='clave_unidad_sat',
            field=models.CharField(default='H87', help_text='Clave de unidad de medida SAT (ej. H87 para Pieza, KGM para Kilogramo)', max_length=10, verbose_name='Clave Unidad SAT'),
        ),
    ]
