# Generated by Django 6.0.6 on 2026-07-01 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC del Cliente')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Nombre o Razón Social (Exacto SAT)')),
                ('regimen_fiscal', models.CharField(max_length=3, verbose_name='Código de Régimen Fiscal (Ej. 601)')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Código Postal del Domicilio Fiscal')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo para Envío de Facturas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True, verbose_name='Folio de Venta')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_cambio_vuelo', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tipo de Cambio del Día')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de Pago'), ('PAG', 'Pagada'), ('FAC', 'Facturada (CFDI Emitido)'), ('CAN', 'Cancelada')], default='PEN', max_length=3)),
                ('uso_cfdi', models.CharField(choices=[('G01', 'Adquisición de mercancías'), ('G03', 'Gastos en general'), ('P01', 'Por definir'), ('CP01', 'Pagos')], default='G03', max_length=4, verbose_name='Uso de CFDI')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='IVA (16%)')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cfdi_uuid', models.UUIDField(blank=True, null=True, verbose_name='UUID Fiscal (Folio Fiscal SAT)')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='cfdi_xmls/', verbose_name='Archivo XML SAT')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente', verbose_name='Cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.moneda', verbose_name='Moneda de Venta')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Cobrado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
        ),
    ]
