# Generated by Django 6.0.6 on 2026-10-05 19:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['razon_social'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar para deshabilitar ventas a este cliente sin borrar historial', verbose_name='Cliente Activo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, help_text='0 para operaciones de contado', verbose_name='Días de Crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección / Domicilio de Entrega'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Límite de Crédito (MXN)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, help_text='Nombre de uso cotidiano o marca conocida', max_length=200, null=True, verbose_name='Nombre Comercial / Identificador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas u Observaciones'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uso_cfdi',
            field=models.CharField(choices=[('G01', 'G01 - Adquisición de mercancías'), ('G02', 'G02 - Devoluciones, descuentos o bonificaciones'), ('G03', 'G03 - Gastos en general'), ('I01', 'I01 - Construcciones'), ('I02', 'I02 - Mobiliario y equipo de oficina'), ('I03', 'I03 - Equipo de transporte'), ('I04', 'I04 - Equipo de cómputo y accesorios'), ('I08', 'I08 - Otra maquinaria y equipo'), ('S01', 'S01 - Sin efectos fiscales'), ('CP01', 'CP01 - Pagos')], default='G03', max_length=4, verbose_name='Uso de CFDI Habitual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(help_text='Código Postal del domicilio fiscal registrado en el SAT', max_length=5, verbose_name='Código Postal Fiscal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(help_text='Destinatario principal de facturas XML/PDF y cotizaciones', max_length=254, verbose_name='Correo para Facturación / Envío'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(help_text='Tal como aparece en la Constancia de Situación Fiscal (en mayúsculas)', max_length=200, verbose_name='Nombre o Razón Social (Exacto SAT)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.CharField(choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('605', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', '606 - Arrendamiento'), ('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'), ('620', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', '621 - Incorporación Fiscal'), ('625', '625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', '626 - Régimen Simplificado de Confianza (RESICO)'), ('616', '616 - Sin obligaciones fiscales')], default='601', max_length=3, verbose_name='Régimen Fiscal (SAT)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(help_text='12 caracteres para Personas Morales o 13 para Personas Físicas', max_length=13, unique=True, verbose_name='RFC del Cliente'),
        ),
    ]
