# Generated by Django 6.0.6 on 2026-10-05 19:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_moneda_options_alter_tipocambio_options_and_more'),
        ('inventario', '0007_movimientoinventario_es_anulado_and_more'),
        ('ventas', '0002_alter_cliente_options_cliente_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='moneda',
        ),
        migrations.CreateModel(
            name='PedidoVenta_Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Folio Comercial')),
                ('tipo_documento', models.CharField(choices=[('COT', 'Cotización'), ('PED', 'Pedido de Venta')], default='PED', max_length=3, verbose_name='Tipo de Documento')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha Compromiso de Entrega')),
                ('tipo_cambio_aplicado', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Tipo de cambio oficial vigente en MXN', max_digits=18, verbose_name='Tipo de Cambio Oficial Aplicado')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COTIZADO', 'Cotización Emitida'), ('CONFIRMADO', 'Confirmado (Pedido en Firme)'), ('SURTIDO', 'Surtido / Remisionado'), ('FACTURADO', 'Facturado (CFDI Emitido)'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=15, verbose_name='Estado Operativo')),
                ('condiciones_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condiciones de Pago')),
                ('referencia_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Orden de Compra del Cliente / Ref')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Instrucciones de Entrega')),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='Tasa de IVA (%)')),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Subtotal')),
                ('impuestos', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='IVA (16%)')),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Total')),
                ('total_mxn', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Total Valuado en MXN')),
                ('uso_cfdi', models.CharField(default='G03', max_length=4, verbose_name='Uso de CFDI')),
                ('metodo_pago', models.CharField(choices=[('PUE', 'PUE - Pago en una sola exhibición'), ('PPD', 'PPD - Pago en parcialidades o diferido')], default='PUE', max_length=3, verbose_name='Método de Pago')),
                ('forma_pago', models.CharField(choices=[('01', '01 - Efectivo'), ('02', '02 - Cheque nominativo'), ('03', '03 - Transferencia electrónica de fondos'), ('99', '99 - Por definir')], default='03', max_length=3, verbose_name='Forma de Pago')),
                ('cfdi_uuid', models.UUIDField(blank=True, null=True, verbose_name='UUID Fiscal SAT')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='cfdi_xmls/', verbose_name='Archivo XML SAT')),
                ('bodega_despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venta', to='inventario.bodega', verbose_name='Almacén de Despacho')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='ventas.cliente', verbose_name='Cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.moneda', verbose_name='Moneda de Venta')),
            ],
            options={
                'verbose_name': 'Pedido de Venta',
                'verbose_name_plural': 'Pedidos de Venta',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='PedidoVenta_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Precio Unitario')),
                ('subtotal_linea', models.DecimalField(decimal_places=6, editable=False, max_digits=18, verbose_name='Subtotal Partida')),
                ('cantidad_surtida', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, verbose_name='Cantidad Surtida / Entregada')),
                ('notas_linea', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notas de Partida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto Vendido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedidoventa_maestro')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido de Venta',
                'verbose_name_plural': 'Detalles de Pedido de Venta',
            },
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
