# Generated by Django 6.0.6 on 2026-10-05 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_cliente_remove_venta_moneda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoventa_maestro',
            name='fecha_surtido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Surtido / Despacho'),
        ),
        migrations.AddField(
            model_name='pedidoventa_maestro',
            name='stock_reservado',
            field=models.BooleanField(default=False, help_text='Indica si el stock de este pedido fue apartado físicamente en el almacén', verbose_name='Stock Reservado en Bodega'),
        ),
        migrations.AddField(
            model_name='pedidoventa_maestro',
            name='usuario_surtio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_surtidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Despachó el Pedido'),
        ),
    ]
