# Generated by Django 6.0.6 on 2026-10-05 22:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_moneda_options_alter_tipocambio_options_and_more'),
        ('inventario', '0008_producto_clave_sat_producto_clave_unidad_sat'),
        ('ventas', '0004_pedidoventa_maestro_fecha_surtido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('I', 'I - Ingreso (Factura)'), ('P', 'P - Pago (Complemento de Recepción de Pagos)'), ('E', 'E - Egreso (Nota de Crédito)')], default='I', max_length=1, verbose_name='Tipo de Comprobante')),
                ('serie', models.CharField(default='F', max_length=10, verbose_name='Serie')),
                ('folio', models.CharField(max_length=20, verbose_name='Folio Fiscal')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='Folio Fiscal SAT (UUID)')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Certificación SAT')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('TIMBRADA', 'Timbrada / Vigente'), ('CANCELADA', 'Cancelada')], default='TIMBRADA', max_length=15, verbose_name='Estado Fiscal')),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Tipo de Cambio')),
                ('metodo_pago', models.CharField(choices=[('PUE', 'PUE - Pago en una sola exhibición'), ('PPD', 'PPD - Pago en parcialidades o diferido')], default='PPD', max_length=3, verbose_name='Método de Pago')),
                ('forma_pago', models.CharField(choices=[('01', '01 - Efectivo'), ('02', '02 - Cheque nominativo'), ('03', '03 - Transferencia electrónica de fondos'), ('04', '04 - Tarjeta de crédito'), ('28', '28 - Tarjeta de débito'), ('99', '99 - Por definir')], default='99', max_length=3, verbose_name='Forma de Pago')),
                ('uso_cfdi', models.CharField(default='G01', max_length=4, verbose_name='Uso de CFDI')),
                ('condiciones_pago', models.CharField(blank=True, max_length=150, null=True, verbose_name='Condiciones de Pago')),
                ('orden_compra_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Orden de Compra / Ref')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Descuento')),
                ('impuestos_trasladados', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='IVA Trasladado (16%)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Comprobante')),
                ('total_mxn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total en MXN')),
                ('saldo_insoluto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Saldo Insoluto Restante')),
                ('pagada', models.BooleanField(default=False, help_text='Indica si la factura está totalmente cobrada (saldo insoluto = 0)', verbose_name='Factura Liquidada')),
                ('no_certificado_emisor', models.CharField(default='00001000000502019816', max_length=30, verbose_name='Serie Certificado Sello Digital (Emisor)')),
                ('no_certificado_sat', models.CharField(default='00001000000504204441', max_length=30, verbose_name='Serie Certificado Sello Digital SAT')),
                ('rfc_prov_certif', models.CharField(default='TSP080724QW6', max_length=15, verbose_name='RFC Proveedor Certificación (PAC)')),
                ('sello_cfd', models.TextField(blank=True, null=True, verbose_name='Sello Digital del Contribuyente (CFDI)')),
                ('sello_sat', models.TextField(blank=True, null=True, verbose_name='Sello Digital del SAT')),
                ('cadena_original', models.TextField(blank=True, null=True, verbose_name='Cadena Original de Certificación SAT')),
                ('xml_firmado', models.FileField(blank=True, null=True, upload_to='cfdi/xml/', verbose_name='Archivo XML Sellado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas del Comprobante')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='ventas.cliente', verbose_name='Cliente Receptor')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.moneda', verbose_name='Moneda')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='ventas.pedidoventa_maestro', verbose_name='Pedido de Venta Origen')),
            ],
            options={
                'verbose_name': 'Factura / CFDI',
                'verbose_name_plural': 'Facturas y CFDI 4.0',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Factura_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_prod_serv', models.CharField(default='24121800', help_text='Clave oficial SAT (ej. 24121800 para recipientes o empaques de hojalata)', max_length=10, verbose_name='Clave Prod/Serv SAT')),
                ('no_identificacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Identificación / SKU')),
                ('clave_unidad', models.CharField(default='H87', help_text='Clave oficial SAT (ej. H87 = Pieza, KGM = Kilogramo)', max_length=10, verbose_name='Clave Unidad SAT')),
                ('unidad', models.CharField(default='Pieza', max_length=50, verbose_name='Nombre de Unidad')),
                ('descripcion', models.TextField(verbose_name='Descripción del Concepto')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Valor Unitario')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Importe')),
                ('objeto_imp', models.CharField(default='02', max_length=3, verbose_name='Objeto de Impuesto')),
                ('base_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Base de IVA')),
                ('tasa_iva', models.DecimalField(decimal_places=4, default=Decimal('0.160000'), max_digits=6, verbose_name='Tasa de IVA')),
                ('importe_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Importe IVA')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.factura_maestro')),
            ],
            options={
                'verbose_name': 'Concepto de Factura',
                'verbose_name_plural': 'Conceptos de Factura',
            },
        ),
        migrations.CreateModel(
            name='ComplementoPago_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parcialidad', models.PositiveIntegerField(default=1, verbose_name='Número de Parcialidad')),
                ('imp_saldo_ant', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Importe Saldo Anterior')),
                ('imp_pagado', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Importe Pagado')),
                ('imp_saldo_insoluto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Importe Saldo Insoluto')),
                ('equivalencia_dr', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Equivalencia DR')),
                ('base_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Base IVA del Pago')),
                ('importe_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Importe IVA del Pago')),
                ('factura_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to='ventas.factura_maestro', verbose_name='Factura Liquidada / Amortizada')),
                ('pago_cfdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctos_relacionados', to='ventas.factura_maestro', verbose_name='Comprobante de Pago (Tipo P)')),
            ],
            options={
                'verbose_name': 'Documento Relacionado de Pago',
                'verbose_name_plural': 'Documentos Relacionados de Pagos',
            },
        ),
    ]
