# Generated by Django 6.0.6 on 2026-10-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_factura_maestro_factura_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_contacto',
            field=models.CharField(blank=True, help_text='Persona responsable de compras / atención comercial del cliente', max_length=150, null=True, verbose_name='Nombre del Contacto'),
        ),
    ]
