"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nkeb+)09v=dhpa8y*gbq%(3+s#)dfmb)3i@v-13)+im6l!ae!@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'general',
    'inventario',
    'compras',
    'ventas',
    'produccion',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os
STATIC_URL = 'static/'

# Esta carpeta solo se usa en producción, no debe ser igual a tus carpetas de desarrollo
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Agrega esta línea si no existe para ayudar a Django a mapear las rutas en desarrollo:
STATICFILES_DIRS = [
    BASE_DIR/ 'static',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Redirigir a los usuarios no autenticados al login del administrador
LOGIN_URL = '/admin/login/'

# Media files (Archivos XML y PDF generados)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==============================================================================
# CONFIGURACIÓN BANXICO SIE (SISTEMA DE INFORMACIÓN ECONÓMICA)
# ==============================================================================
# Token gratuito generado en: https://www.banxico.org.mx/SieAPIRest/service/v1/token
BANXICO_TOKEN = os.environ.get('BANXICO_TOKEN', 'a80faf28e45f6fa83728bc8d626c7529473ac7826aef826343908a9f723d790e')
BANXICO_API_BASE_URL = 'https://www.banxico.org.mx/SieAPIRest/service/v1/'
BANXICO_SERIES = {
    'USD': 'SF43718',  # Tipo de cambio FIX para solventar obligaciones (DOF / CFF Art. 20)
    'EUR': 'SF46410',  # Cotización Euro frente al peso mexicano (Canasta DEG)
}

# ==============================================================================
# CONFIGURACIÓN FISCAL SAT CFDI 4.0 - DECORLATA S.A. DE C.V.
# ==============================================================================
CFDI_EMISOR_RFC = os.environ.get('CFDI_EMISOR_RFC', 'DEC150115B42')
CFDI_EMISOR_NOMBRE = os.environ.get('CFDI_EMISOR_NOMBRE', 'DECORLATA S.A. DE C.V.')
CFDI_EMISOR_REGIMEN = os.environ.get('CFDI_EMISOR_REGIMEN', '601')
CFDI_LUGAR_EXPEDICION = os.environ.get('CFDI_LUGAR_EXPEDICION', '56255')
CFDI_DOMICILIO_PLANTA = (
    'GRAL. MARIANO RUIZ No.121, SANTIAGO CUAUTLALPAN, Texcoco Edo. Mex. C.P. 56255'
)
CFDI_NO_CERTIFICADO_EMISOR = os.environ.get('CFDI_NO_CERTIFICADO_EMISOR', '00001000000502019816')
CFDI_NO_CERTIFICADO_SAT = os.environ.get('CFDI_NO_CERTIFICADO_SAT', '00001000000504204441')
CFDI_PAC_RFC_PROV = os.environ.get('CFDI_PAC_RFC_PROV', 'TSP080724QW6')

