# Generated by Django 6.0.6 on 2026-07-01 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código ISO')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Moneda')),
                ('simbolo', models.CharField(max_length=5, verbose_name='Simbolo ($, €, etc.)')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedass',
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_en_mxn', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor en MXN')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Actualización')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='general.moneda')),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'unique_together': {('moneda_origen', 'fecha')},
            },
        ),
    ]
