# Generated by Django 6.0.6 on 2026-07-01 21:49

from django.db import migrations

def crear_grupos_y_permisos(apps, schema_editor):
    # Obtenemos los modelos nativos de Django para Grupos y Permisos
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    # 1. Definimos los roles principales del ERP
    roles = {
        'Administrador_ERP': {
            'descripcion': 'Acceso total a todas las operaciones y configuraciones del sistema.',
            'modulos': ['general', 'inventario', 'compras', 'ventas', 'produccion']
        },
        'Encargado_Almacen': {
            'descripcion': 'Gestión de existencias, entradas de compras y consumos de producción.',
            'modulos': ['inventario']
        },
        'Agente_Ventas': {
            'descripcion': 'Creación de cotizaciones, pedidos y emisión de facturas CFDI 4.0.',
            'modulos': ['ventas', 'inventario'] # Necesita inventario para ver existencias
        },
        'Supervisor_Produccion': {
            'descripcion': 'Control de listas de materiales (BOM) y órdenes de fabricación.',
            'modulos': ['produccion', 'inventario'] # Necesita inventario para ver insumos
        }
    }

    # 2. Creamos los grupos y les asignamos sus permisos correspondientes
    for nombre_rol, info in roles.items():
        grupo, created = Group.objects.get_or_create(name=nombre_rol)
        
        # Si es Administrador, le damos todos los permisos disponibles del sistema
        if nombre_rol == 'Administrador_ERP':
            todos_los_permisos = Permission.objects.all()
            grupo.permissions.set(todos_los_permisos)
        else:
            # Para los demás roles, filtramos los permisos por el nombre de la app (módulo)
            permisos_filtrados = Permission.objects.filter(
                content_type__app_label__in=info['modulos']
            )
            grupo.permissions.set(permisos_filtrados)

def eliminar_grupos_y_permisos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Administrador_ERP', 'Encargado_Almacen', 'Agente_Ventas', 'Supervisor_Produccion']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'), # Asegúrate de que apunte a tu primera migración
        ('auth', '0012_alter_user_first_name_max_length'), # Dependencia nativa de Django Auth
    ]

    operations = [
        migrations.RunPython(crear_grupos_y_permisos, reverse_code=eliminar_grupos_y_permisos),
    ]
