# Generated by Django 6.0.6 on 2026-09-30 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_crear_roles_erp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterModelOptions(
            name='tipocambio',
            options={'ordering': ['-fecha', 'moneda_origen'], 'verbose_name': 'Tipo de Cambio', 'verbose_name_plural': 'Tipos de Cambio'},
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='fuente',
            field=models.CharField(default='BANXICO_FIX', max_length=50, verbose_name='Fuente / Mecanismo'),
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Tipo de Cambio'),
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='valor_en_mxn',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor en MXN'),
        ),
    ]
