# Generated by Django 6.0.6 on 2026-07-01 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaMaterialesBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_base', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Para producir (Cantidad base)')),
                ('descripcion_proceso', models.TextField(blank=True, null=True, verbose_name='Instrucciones de Manufactura')),
                ('producto_terminado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta_bom', to='inventario.producto', verbose_name='Producto Terminado a Fabricar')),
            ],
            options={
                'verbose_name': 'Lista de Materiales (BOM)',
                'verbose_name_plural': 'Listas de Materiales (BOM)',
            },
        ),
        migrations.CreateModel(
            name='InsumoBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cantidad Requerida')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_como_insumo', to='inventario.producto', verbose_name='Materia Prima / Insumo')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='produccion.listamaterialesbom')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True, verbose_name='No. Orden de Producción')),
                ('cantidad_a_producir', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Solicitada')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PLA', 'Planeada / Cola de Espera'), ('PRO', 'En Proceso de Fabricación'), ('TER', 'Terminada (Stock Incrementado)'), ('CAN', 'Cancelada')], default='PLA', max_length=3)),
                ('producto_a_fabricar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto a Fabricar')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
            },
        ),
    ]
