# Generated by Django 6.0.6 on 2026-09-08 23:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_tipo'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumobom',
            options={'verbose_name': 'Insumo de Receta', 'verbose_name_plural': 'Insumos de Receta'},
        ),
        migrations.AlterModelOptions(
            name='listamaterialesbom',
            options={'ordering': ['producto_terminado__nombre'], 'verbose_name': 'Lista de Materiales (BOM)', 'verbose_name_plural': 'Listas de Materiales (BOM)'},
        ),
        migrations.AlterModelOptions(
            name='ordenproduccion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Orden de Producción', 'verbose_name_plural': 'Órdenes de Producción'},
        ),
        migrations.AddField(
            model_name='insumobom',
            name='porcentaje_merma',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje adicional contemplado por mermas del proceso', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='% Merma / Scrap Esperado'),
        ),
        migrations.AddField(
            model_name='listamaterialesbom',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Receta Activa'),
        ),
        migrations.AddField(
            model_name='listamaterialesbom',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listamaterialesbom',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='bodega_destino_pt',
            field=models.ForeignKey(blank=True, help_text='Almacén al cual ingresará el lote terminado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ops_destino', to='inventario.bodega', verbose_name='Bodega Destino (Producto Fabricado)'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='bodega_origen_insumos',
            field=models.ForeignKey(blank=True, help_text='Almacén del cual se tomarán las materias primas y componentes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ops_origen', to='inventario.bodega', verbose_name='Bodega de Insumos / Materia Prima'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='produccion.listamaterialesbom', verbose_name='Fórmula / BOM Utilizada'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad_producida',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Cantidad Producida Real'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='costo_total_insumos_mxn',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, verbose_name='Costo Total Insumos (MXN)'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='costo_unitario_final_mxn',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, verbose_name='Costo Unitario Resultante (MXN)'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_compromiso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Compromiso de Entrega'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='lote_fabricacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote de Fabricación'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Proceso'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ops_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='usuario_finalizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ops_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por'),
        ),
        migrations.AlterField(
            model_name='insumobom',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='produccion.listamaterialesbom', verbose_name='Receta BOM'),
        ),
        migrations.AlterField(
            model_name='insumobom',
            name='cantidad_requerida',
            field=models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Cantidad Requerida'),
        ),
        migrations.AlterField(
            model_name='listamaterialesbom',
            name='cantidad_base',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Ej: 1 para 1 pza, 1000 para un millar de botes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Cantidad Base de Fabricación'),
        ),
        migrations.AlterField(
            model_name='listamaterialesbom',
            name='descripcion_proceso',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucciones y Ruta de Manufactura'),
        ),
        migrations.AlterField(
            model_name='listamaterialesbom',
            name='producto_terminado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta_bom', to='inventario.producto', verbose_name='Producto a Fabricar'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='cantidad_a_producir',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Cantidad Solicitada'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('PLA', 'Planeada / En Espera'), ('PRO', 'En Proceso de Fabricación'), ('TER', 'Terminada (Stock Afectado)'), ('CAN', 'Cancelada')], default='PLA', max_length=3, verbose_name='Estado de Producción'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='folio',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='No. Orden de Producción'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='producto_a_fabricar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_fabricacion', to='inventario.producto', verbose_name='Producto a Fabricar'),
        ),
        migrations.AlterUniqueTogether(
            name='insumobom',
            unique_together={('bom', 'materia_prima')},
        ),
        migrations.CreateModel(
            name='OrdenProduccion_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estimada', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Cantidad Proyectada')),
                ('cantidad_consumida', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=14, verbose_name='Cantidad Real Consumida')),
                ('costo_unitario_mxn', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, verbose_name='Costo Unitario Capturado (MXN)')),
                ('costo_total_mxn', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, verbose_name='Costo Total Línea (MXN)')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_ordenes', to='inventario.producto', verbose_name='Insumo / Materia Prima')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_detalle', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Insumo de Orden de Producción',
                'verbose_name_plural': 'Insumos de Orden de Producción',
                'unique_together': {('orden', 'insumo')},
            },
        ),
    ]
