# Generated by Django 6.0.6 on 2026-09-16 23:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_tipo'),
        ('produccion', '0002_alter_insumobom_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaParcialProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_entrega', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Folio de Entrega')),
                ('cantidad_notificada', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Cantidad Notificada (PT)')),
                ('lote_fabricacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote Fabricado')),
                ('fecha_notificacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Notificación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Autorización de Almacén'), ('AUTORIZADA', 'Autorizada (Ingresada al Kardex)'), ('RECHAZADA', 'Rechazada por Almacén')], default='PENDIENTE', max_length=15, verbose_name='Estado de Autorización')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('notas_almacen', models.TextField(blank=True, null=True, verbose_name='Observaciones / Motivo de Almacén')),
                ('observaciones_produccion', models.TextField(blank=True, null=True, verbose_name='Notas del Turno / Producción')),
                ('costo_total_insumos_mxn', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, verbose_name='Costo Total Insumos (MXN)')),
                ('costo_unitario_final_mxn', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, verbose_name='Costo Unitario Resultante (MXN)')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_parciales', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
                ('usuario_autoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por (Almacén)')),
                ('usuario_notifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_notificadas', to=settings.AUTH_USER_MODEL, verbose_name='Notificado por')),
            ],
            options={
                'verbose_name': 'Entrega Parcial de Producción',
                'verbose_name_plural': 'Entregas Parciales de Producción',
                'ordering': ['-fecha_notificacion'],
            },
        ),
        migrations.CreateModel(
            name='EntregaParcial_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estimada', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Cantidad Estimada')),
                ('cantidad_consumida', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=14, verbose_name='Cantidad Consumida')),
                ('costo_unitario_mxn', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, verbose_name='Costo Unitario Capturado (MXN)')),
                ('costo_total_mxn', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, verbose_name='Costo Total Línea (MXN)')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_en_entregas', to='inventario.producto', verbose_name='Insumo / Materia Prima')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_detalle', to='produccion.entregaparcialproduccion', verbose_name='Entrega Parcial')),
            ],
            options={
                'verbose_name': 'Insumo de Entrega Parcial',
                'verbose_name_plural': 'Insumos de Entregas Parciales',
                'unique_together': {('entrega', 'insumo')},
            },
        ),
    ]
