# Generated by Django 6.0.6 on 2026-10-05 23:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_entregaparcialproduccion_entregaparcial_insumo'),
        ('ventas', '0005_factura_maestro_factura_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='pedido_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to='ventas.pedidoventa_detalle', verbose_name='Partida de Pedido Específica'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='pedido_venta',
            field=models.ForeignKey(blank=True, help_text='Pedido comercial en firme que originó esta orden de producción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to='ventas.pedidoventa_maestro', verbose_name='Pedido de Venta Relacionado'),
        ),
        migrations.CreateModel(
            name='EtapaProduccionOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_etapa', models.CharField(choices=[('CORTE_HOJA', '1. Cizallado Primario de Hojalata'), ('LITOGRAFIA', '2. Litografía y Barnizado'), ('CORTE_CUERPO', '3. Corte de Plantillas (Cuerpos)'), ('SOLDADURA', '4. Formado y Soldadura Eléctrica'), ('ENSAMBLE', '5. Línea de Ensamble y Engargolado'), ('PRUEBA_EMPAQUE', '6. Prueba de Hermeticidad y Paletizado')], max_length=25, verbose_name='Estación / Etapa Industrial')),
                ('nombre_etapa', models.CharField(max_length=120, verbose_name='Nombre de la Estación')),
                ('secuencia', models.PositiveIntegerField(default=1, verbose_name='Secuencia en Línea')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=15, verbose_name='Estado de la Estación')),
                ('cantidad_entrada', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Cantidad Recibida en Estación')),
                ('cantidad_buena', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Piezas Conformes / Procesadas')),
                ('cantidad_scrap', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Merma / Scrap (Piezas Defectuosas)')),
                ('operador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Operador / Líder de Línea')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio en Estación')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin en Estación')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Observaciones de Calidad / Proceso')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_ensamble', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Etapa de Línea de Ensamble',
                'verbose_name_plural': 'Etapas de Líneas de Ensamble',
                'ordering': ['secuencia', 'id'],
                'unique_together': {('orden', 'codigo_etapa')},
            },
        ),
    ]
