# Generated by Django 6.0.6 on 2026-07-01 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC del Proveedor')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True, verbose_name='Folio de Compra')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('tipo_cambio_vuelo', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tipo de Cambio Aplicado')),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('SOL', 'Solicitada'), ('REC', 'Recibida Totalmente'), ('CAN', 'Cancelada')], default='BOR', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.moneda', verbose_name='Moneda de la Operación')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario (Divisa Original)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra')),
            ],
        ),
    ]
