# Generated by Django 6.0.6 on 2026-08-21 22:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('general', '0002_crear_roles_erp'),
        ('inventario', '0003_movimientoinventario_costo_unitario_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto_nombre',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='correo',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_credito',
            field=models.IntegerField(default=0, help_text='Días de crédito otorgados por el proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(max_length=15, unique=True, verbose_name='RFC / Tax ID'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrdenCompra_Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_esperada', models.DateField(blank=True, null=True)),
                ('tipo_cambio_aplicado', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Se captura automáticamente al autorizar/recibir si la moneda no es local', max_digits=18)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUTORIZADA', 'Autorizada (Pendiente de Recepción)'), ('RECIBIDA', 'Recibida (Ingresada a Almacén)'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('impuestos', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('bodega_destino', models.ForeignKey(help_text='Almacén donde se recibirá la mercancía', on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('subtotal_linea', models.DecimalField(decimal_places=6, editable=False, max_digits=18)),
                ('cantidad_recibida', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra_maestro')),
            ],
        ),
        migrations.DeleteModel(
            name='DetalleOrdenCompra',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
    ]
